version: "3.9"
services:
  gubber:
    container_name: gubber
    restart: unless-stopped
    image: ghcr.io/josiahbull/gubber:main
    volumes:
      - ${LOCATION}:/respository
    environment:
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      LOCATION: /repsoitory
      INTERVAL: ${INTERVAL:-86400}
      BACKUPS: ${BACKUPS:-30}