version: "3.9"
services:
  gubber:
    container_name: gubber
    restart: unless-stopped
    # image: ghcr.io/josiahbull/gubber:main
    build: .
    volumes:
      - ./repository:/app/repository
    environment:
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      LOCATION: ./repository
      TEMP_LOCATION: /tmp
      INTERVAL: ${INTERVAL:-86400}
      BACKUPS: ${BACKUPS:-30}