name: Run golangci-lint
on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  golangci:
    name: lint checker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-go@v4

      - name: Run golang-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: --timeout=10m
