name: precommit

on: [push]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
    - name: pre-commit
      run: |
        python -m pip install --upgrade pip
        pip install pre-commit
        pre-commit run --all-files
